version: 0.0

os: linux

files:
  - source: ./
    destination: /home/ubuntu/skillook-node

hooks:
  AfterInstall:
    - location: cicd/scripts/afterInstall.sh
      runas: root

  BeforeInstall:
    - location: cicd/scripts/beforeInstall.sh
      runas: root
